### ISSUE TITLE
Serializing `enum`, `const` etc members of Aggregate

### ISSUE THREAD

**Issue by drug007** [libmir/asdf#78] opened 2017-10-03 17:31 UTC
Consider:
```
unittest
{
	static struct S
	{
		enum A = 200;
		const float B = 10f;
		float f;
		int i;
	}

	assert (serializeToJson(S()) == `{"A":200,"B":10,"f":nan,"i":0}`);
}
```
I'm not sure about nesseccerity to (de)serialize `A` and `B` member. What do you think?

**Comment by 9il** [comment] 2017-10-03 17:54
enum and _static_ members should not be (de)serialized. const members should be.

**Comment by yannick** [comment] 2017-10-04 07:51
hmm, i think its okish to not deserialize them per default, however i think it should be made possible via annotations in order to really re-instantiate the state of the class correctly. should already be supported via methods but should be explicitly mentioned in the docs.

**Comment by drug007** [comment] 2017-10-04 08:09
Unfortunately, I didn't find the way to detect anonymous enum like `enum A = 100;`, because
 `is (typeof(A) == enum)` [doesn't work](https://run.dlang.io/is/dZD2qT).

**Comment by 9il** [comment] 2017-10-04 08:28
They way is simple: enums does not have an address.

**Comment by drug007** [comment] 2017-10-04 09:39
Yes, but templates have no address too, so it's not such simple.

**Comment by drug007** [comment] 2017-10-05 18:12
> const members should be.

@9il  Because const members can not be deserialized, should they be checked for equality - value from aggregate itself and value from deserialized data?

**Comment by 9il** [comment] 2018-09-09 12:29
> @9il Because const members can not be deserialized, should they be checked for equality - value from aggregate itself and value from deserialized data?

nope

**Comment by nexor** [comment] 2019-07-08 20:04
@9il 
I've noticed that since v0.4.9 serialization of immutable struct members has been changed.
The following code:
```d
import asdf, std.stdio;

struct Payload
{
    immutable im = "value";
    bool flag;
}

void main()
{
	Payload p = {
          flag: true 
	};

    writeln(p.serializeToJson());
}
```
on 0.4.8 produces:
`{"flag":true}`

however, on 0.4.9 it produces:
`{"im":"value","flag":true}`

Is this intended behavior or regression bug?

**Comment by 9il** [comment] 2019-07-09 08:30
Yes, all public members of an instance should be serialized if that is not prohibited by ASDF attributes or custom serialization function. You can mark this additionally with `static` or `enum`: needs v0.4.10, just released.

**Comment by 9il** [comment] 2019-07-09 08:31
Fixed for const/immutable members of instance. Won't be fixed for enum and static members.

**Closed by 9il** 2019-07-09 08:31 UTC
Labels: bug
