### ISSUE TITLE
Error when trying to compile typed enums

### ISSUE THREAD

**Issue by nexor** [libmir/asdf#94] opened 2018-04-08 00:28 UTC
**Code:**
```d
#!/usr/bin/env dub
/+ dub.sdl:
    dependency "asdf" version="~>0.2.2"
+/

import asdf;

enum SimpleEnum : string
{
    se1 = "se1value",
    se2 = "se1value"
}

struct Simple
{
    SimpleEnum en;
}

int main(string[] args)
{
    Simple simple = `{"en":"se1value"}`.deserialize!(Simple);

    return 0;
}
```

**Result:**
```
$ ./asdferror.d 
../../.dub/packages/asdf-0.2.2/asdf/source/asdf/serialization.d(2208,12): Error: asdf.serialization.deserializeValue called with argument types (Asdf, SimpleEnum) matches both:
../../.dub/packages/asdf-0.2.2/asdf/source/asdf/serialization.d(1807,6):     asdf.serialization.deserializeValue!(SimpleEnum).deserializeValue(Asdf data, ref SimpleEnum value)
and:
../../.dub/packages/asdf-0.2.2/asdf/source/asdf/serialization.d(1861,6):     asdf.serialization.deserializeValue!(SimpleEnum).deserializeValue(Asdf data, ref SimpleEnum value)
../../.dub/packages/asdf-0.2.2/asdf/source/asdf/serialization.d(370,18): Error: template instance `asdf.serialization.deserializeValue!(Simple)` error instantiating
../../.dub/packages/asdf-0.2.2/asdf/source/asdf/serialization.d(379,22):        instantiated from here: deserialize!(Simple)
asdferror.d(21,25):        instantiated from here: deserialize!(Simple)
/usr/bin/dmd failed with exit code 1.
```

**Expected:** successful compilation and after compilation, `simple.en` has the value `SimpleEnum.se1`

**Comment by drug007** [comment] 2018-11-17 17:57
@9il  It is a duplicate of #97  - in fact typed enum compile fine except string based.

**Closed** 2018-12-11 14:05 UTC

**Comment by 9il** [comment] 2019-07-07 17:40
Both enum keys and enum string values now supported for deserialization.

**Comment by 9il** [comment] 2019-07-07 17:58
https://github.com/libmir/asdf/releases/tag/v0.4.9
